# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

News:
  fields:
    list: title, author, post_date
    form: title, author, post, post_date
    show: id, title, author, post, post_date, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships: 
  filters:
  search:
  application: itsaconference
  description:

