# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

Rating:
  fields:
    list: value, item_id, item_type, user_id
    form: value, item_id, item_type, user_id
    show: id, value, item_id, item_type, user_id, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships: 
  filters:
  search:
  application: itsaconference
  description:

